#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=29gb,walltime=00:30:00
#PBS -N app-freesurfer-stats-subcortical
#PBS -V

set -e

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

mkdir -p parc-stats

time singularity exec -e docker://brainlife/fsl:5.0.9 ./handle_scaling.sh

[ ! -f subcort_cols.txt ] && time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./subcort-stats.sh

if [ ! -f ./parc-stats/aseg_nodes.csv ]; then
	time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./create_data_csv.py
fi

if [ ! -f ./parc-stats/aseg_nodes.csv ]; then
	echo "output missing"
	exit 1
else
	echo "complete" && mkdir -p raw && mv cortexmap/ ./tmp/*.txt ./tmp/*.csv ./tmp/*.sum ./raw/ && rm -rf *.nii.gz tmp
   	exit 0
fi
